version: 1.0.{build}
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
environment:
  ASPNETCORE_ENVIRONMENT: Development
  BUILD_DIR: C:\projects\Tompany
before_build:
- cmd: >-
    dotnet restore
    nuget restore
build:
  project: C:\projects\tompany\Tompany.sln
  publish_aspnet_core: true
  verbosity: minimal 